Fix missing chart canvas element
- Fix missingChart: change from div to canvas inside div
- Matches targetChart pattern: <div class='chart-container'><canvas id='...'></canvas></div>
- Fixes TypeError: getContext is not a function
- Missing values chart should now render properly

Error fixed:
  Before: <div class='chart-container' id='missingChart'></div>
  After:  <div class='chart-container'><canvas id='missingChart'></canvas></div>